# Generated by Django 5.0.6 on 2024-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.IntegerField(default=1, verbose_name='Matricule'),
            preserve_default=False,
        ),
    ]
