# Generated by Django 5.0.6 on 2024-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to='profile/', verbose_name='Profile '),
        ),
    ]
