# Generated by Django 5.0.6 on 2024-09-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_users', 'Can view all users')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
    ]
