# Generated by Django 5.0.6 on 2024-09-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
        ('employer', '0020_remove_employe_user_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employe',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='employer.employe'),
            preserve_default=False,
        ),
    ]
