# Generated by Django 5.0.6 on 2024-09-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employe',
        ),
    ]
