# Generated by Django 5.0.6 on 2024-10-21 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.IntegerField(verbose_name='Matricule')),
                ('name_employe', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom_employe', models.CharField(max_length=25, verbose_name='Prenom')),
                ('date_naiss_employe', models.DateField(verbose_name='Date de Naissance')),
                ('email_employe', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('adresse_employe', models.CharField(max_length=20, verbose_name='Adresse')),
                ('tel_employe', models.CharField(max_length=9, verbose_name='Telephone')),
                ('image_employe', models.ImageField(upload_to='image_Employe/', verbose_name='Image Employer')),
                ('genre_employe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('autre', 'AUTRE')], max_length=10, verbose_name='Genre')),
                ('diplome_employe', models.ImageField(upload_to='image_diplome_employe/', verbose_name='Image Diplome')),
                ('poste_employe', models.CharField(choices=[('DEV', 'Developpeur'), ('RH', 'Gestion Humaine'), ('DG', 'Directeur Generale'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier'), ('autre', 'AUTRE')], max_length=5, verbose_name='Poste')),
                ('contrat_employe', models.CharField(choices=[('CDD', 'Contrat a dure determiner'), ('CDI', 'Contrat a dure indetermine'), ('autre', 'AUTRE')], max_length=5, verbose_name='Contrat')),
                ('service_employe', models.CharField(choices=[('SD', 'Service de Developpement'), ('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine'), ('autre', 'AUTRE')], max_length=5, verbose_name='Service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employes',
                'permissions': [('view_all_employes', 'Can view all employes')],
            },
        ),
        migrations.CreateModel(
            name='Abscence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=8)),
                ('type_abscence', models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgMt', 'Conge Maternite'), ('cgE', 'Conge Entreprise'), ('autre', 'AUTRE')], max_length=5, verbose_name='Type de Conge')),
                ('date_debut', models.DateField(verbose_name='Date de debut')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date de Paiement ')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total ')),
                ('type_paiement', models.CharField(choices=[('CASH', 'Espece'), ('CHECK', 'Cheque'), ('prime', 'Prime'), ('remboursement', 'Remboursement'), ('autre', 'AUTRE')], max_length=13, verbose_name='Type de Paiement ')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=8, verbose_name='Statut ')),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employe')),
            ],
        ),
    ]
