# Generated by Django 5.0.6 on 2024-09-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employe', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom_employe', models.CharField(max_length=25, verbose_name='Prenom')),
                ('date_naiss_employe', models.DateField(verbose_name='Date de Naissance')),
                ('email_employe', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('adresse_employe', models.CharField(max_length=20, verbose_name='Adresse')),
                ('tel_employe', models.CharField(max_length=9, verbose_name='Telephone')),
                ('image_employe', models.ImageField(upload_to='', verbose_name='Image Employer')),
                ('genre_employe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=1, verbose_name='Genre')),
                ('diplome_employe', models.ImageField(upload_to='', verbose_name='Image Diplome')),
                ('poste_employe', models.CharField(choices=[('RF', 'Responsable Financier'), ('DG', 'Directeur Generale'), ('DT', 'Directeur Technique'), ('RH', 'Gestion Humaine'), ('DEV', 'Developpeur')], max_length=3, verbose_name='Poste')),
                ('contrat_employe', models.CharField(choices=[('CDI', 'Contrat a dure indetermine'), ('CDD', 'Contrat a dure determiner')], max_length=3, verbose_name='Contrat')),
                ('service_employe', models.CharField(choices=[('SRH', 'Services de gestion humaine'), ('SD', 'Service de Developpement'), ('SR', 'Service de Reseau')], max_length=3, verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employes',
            },
        ),
        migrations.CreateModel(
            name='Abscence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abscence', models.CharField(choices=[('cgMt', 'Conge Maternite'), ('cgE', 'Conge Entreprise'), ('cgM', 'Conge Maladie')], max_length=4, verbose_name="Type d'abscence")),
                ('date_debut', models.DateField(verbose_name='Date de debut')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(verbose_name='Date de Paiement ')),
                ('montant_total', models.IntegerField(verbose_name='Montant Total ')),
                ('type_paiement', models.CharField(choices=[('remboursement', 'Remboursement'), ('prime', 'Prime'), ('CHECK', 'Cheque'), ('CASH', 'Espece')], max_length=13, verbose_name='Type de Paiement ')),
                ('status', models.CharField(choices=[('annuler', 'Annuler'), ('valider', 'Valider'), ('en cours ', 'En cours')], max_length=9, verbose_name='Statut ')),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employe')),
            ],
        ),
    ]
