# Generated by Django 5.0.6 on 2024-10-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDI', 'Contrat a dure indetermine'), ('CDD', 'Contrat a dure determiner')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DEV', 'Developpeur'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier'), ('DG', 'Directeur Generale'), ('RH', 'Gestion Humaine')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SD', 'Service de Developpement'), ('SRH', 'Services de gestion humaine'), ('SR', 'Service de Reseau')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CHECK', 'Cheque'), ('CASH', 'Espece'), ('prime', 'Prime'), ('remboursement', 'Remboursement')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
