# Generated by Django 5.0.6 on 2024-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite'), ('cgM', 'Conge Maladie')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='diplome_employe',
            field=models.ImageField(upload_to='image_diplome_employe/', verbose_name='Image Diplome'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='image_employe',
            field=models.ImageField(upload_to='image_Employe/', verbose_name='Image Employer'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DT', 'Directeur Technique'), ('DG', 'Directeur Generale'), ('RF', 'Responsable Financier'), ('DEV', 'Developpeur'), ('RH', 'Gestion Humaine')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine'), ('SD', 'Service de Developpement')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Total '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('en cours ', 'En cours'), ('annuler', 'Annuler'), ('valider', 'Valider')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('prime', 'Prime'), ('CASH', 'Espece'), ('remboursement', 'Remboursement'), ('CHECK', 'Cheque')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
