# Generated by Django 5.0.6 on 2024-10-17 14:54

import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_employe_genre_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgMt', 'Conge Maternite'), ('autre', 'AUTRE'), ('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise')], max_length=5, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CONTRA_A_DURE_INDETERMINER', 'Contrat a dure indetermine'), ('CONTRA_A_DURE_DETERMINER', 'Contrat a dure determiner'), ('autre', 'AUTRE')], max_length=26, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='diplome_employe',
            field=models.FileField(upload_to='image_diplome_employe/', validators=[employer.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre_employe',
            field=models.CharField(choices=[('H', 'Homme'), ('autre', 'AUTRE'), ('F', 'Femme')], max_length=5, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique'), ('DEV', 'Developpeur'), ('DG', 'Directeur Generale'), ('RF', 'Responsable Financier'), ('autre', 'AUTRE')], max_length=5, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SD', 'Service de Developpement'), ('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine'), ('autre', 'AUTRE')], max_length=5, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('PENDING', 'En attente')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CHECK', 'Cheque'), ('remboursement', 'Remboursement'), ('autre', 'AUTRE'), ('CASH', 'Espece'), ('prime', 'Prime')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
