# Generated by Django 5.0.6 on 2024-10-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite'), ('cgM', 'Conge Maladie'), ('autre', 'AUTRE')], max_length=5, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre_employe',
            field=models.CharField(choices=[('F', 'Femme'), ('H', 'Homme'), ('autre', 'AUTRE')], max_length=5, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DEV', 'Developpeur'), ('RF', 'Responsable Financier'), ('autre', 'AUTRE'), ('DG', 'Directeur Generale'), ('DT', 'Directeur Technique')], max_length=5, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvée'), ('PENDING', 'En attente'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('prime', 'Prime'), ('CASH', 'Espece'), ('remboursement', 'Remboursement'), ('autre', 'AUTRE'), ('CHECK', 'Cheque')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
