# Generated by Django 5.0.6 on 2024-10-17 16:09

import employer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='diplome_employe',
            field=models.FileField(upload_to='image_diplome_employe/', validators=[employer.models.validate_file_extension, employer.models.validate_file_size]),
        ),
    ]
