# Generated by Django 5.0.6 on 2024-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_abscence_status_alter_paiement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='genre_employe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('autre', 'AUTRE')], max_length=10, verbose_name='Genre'),
        ),
    ]
