# Generated by Django 5.0.6 on 2024-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_alter_employe_contrat_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDD', 'Contrat a dure determiner'), ('CDI', 'Contrat a dure indetermine')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre_employe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DG', 'Directeur Generale'), ('DEV', 'Developpeur'), ('RF', 'Responsable Financier'), ('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SRH', 'Services de gestion humaine'), ('SD', 'Service de Developpement'), ('SR', 'Service de Reseau')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('valider', 'Valider'), ('en cours ', 'En cours'), ('annuler', 'Annuler')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('prime', 'Prime'), ('CASH', 'Espece'), ('remboursement', 'Remboursement'), ('CHECK', 'Cheque')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
