# Generated by Django 5.0.6 on 2024-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite'), ('cgM', 'Conge Maladie')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre_employe',
            field=models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('RF', 'Responsable Financier'), ('DG', 'Directeur Generale'), ('DEV', 'Developpeur'), ('DT', 'Directeur Technique')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SD', 'Service de Developpement'), ('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('en cours ', 'En cours'), ('valider', 'Valider'), ('annuler', 'Annuler')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('prime', 'Prime'), ('remboursement', 'Remboursement'), ('CHECK', 'Cheque'), ('CASH', 'Espece')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
