# Generated by Django 5.0.6 on 2024-10-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_alter_employe_contrat_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDD', 'Contrat a dure determiner'), ('CDI', 'Contrat a dure indetermine'), ('autre', 'AUTRE')], max_length=5, verbose_name='Contrat'),
        ),
    ]
