# Generated by Django 5.0.6 on 2024-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_alter_employe_contrat_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='diplome_employe',
            field=models.ImageField(upload_to='image_diplome_employe/', verbose_name='Image Diplome'),
        ),
    ]
