# Generated by Django 5.0.6 on 2024-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_alter_employe_poste_employe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgMt', 'Conge Maternite'), ('cgE', 'Conge Entreprise'), ('cgM', 'Conge Maladie')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDD', 'Contrat a dure determiner'), ('CDI', 'Contrat a dure indetermine')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique'), ('DG', 'Directeur Generale'), ('RF', 'Responsable Financier'), ('DEV', 'Developpeur')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SD', 'Service de Developpement'), ('SRH', 'Services de gestion humaine'), ('SR', 'Service de Reseau')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('valider', 'Valider'), ('annuler', 'Annuler'), ('en cours ', 'En cours')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('remboursement', 'Remboursement'), ('prime', 'Prime'), ('CHECK', 'Cheque'), ('CASH', 'Espece')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
