# Generated by Django 5.0.6 on 2024-09-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_employe_user_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDD', 'Contrat a dure determiner'), ('CDI', 'Contrat a dure indetermine')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RF', 'Responsable Financier'), ('DEV', 'Developpeur'), ('DG', 'Directeur Generale'), ('DT', 'Directeur Technique'), ('RH', 'Gestion Humaine')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('annuler', 'Annuler'), ('en cours ', 'En cours'), ('valider', 'Valider')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('remboursement', 'Remboursement'), ('CHECK', 'Cheque'), ('CASH', 'Espece'), ('prime', 'Prime')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
