# Generated by Django 5.0.6 on 2024-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0020_remove_employe_user_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgMt', 'Conge Maternite'), ('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier'), ('DG', 'Directeur Generale'), ('DEV', 'Developpeur')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine'), ('SD', 'Service de Developpement')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('valider', 'Valider'), ('annuler', 'Annuler'), ('en cours ', 'En cours')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('prime', 'Prime'), ('CASH', 'Espece'), ('CHECK', 'Cheque'), ('remboursement', 'Remboursement')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
