# Generated by Django 5.0.6 on 2024-09-24 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_alter_abscence_type_abscence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDI', 'Contrat a dure indetermine'), ('CDD', 'Contrat a dure determiner')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DEV', 'Developpeur'), ('DT', 'Directeur Technique'), ('RH', 'Gestion Humaine'), ('RF', 'Responsable Financier'), ('DG', 'Directeur Generale')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine'), ('SD', 'Service de Developpement')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('annuler', 'Annuler'), ('valider', 'Valider'), ('en cours ', 'En cours')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CHECK', 'Cheque'), ('prime', 'Prime'), ('CASH', 'Espece'), ('remboursement', 'Remboursement')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
