# Generated by Django 5.0.6 on 2024-09-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0024_employe_user_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgMt', 'Conge Maternite'), ('cgE', 'Conge Entreprise')], max_length=4, verbose_name="Type d'abscence"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DEV', 'Developpeur'), ('DG', 'Directeur Generale'), ('RF', 'Responsable Financier'), ('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('valider', 'Valider'), ('annuler', 'Annuler'), ('en cours ', 'En cours')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CASH', 'Espece'), ('CHECK', 'Cheque'), ('prime', 'Prime'), ('remboursement', 'Remboursement')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
