# Generated by Django 5.0.6 on 2024-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0025_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'permissions': [('view_all_employes', 'Can view all employes')], 'verbose_name': 'Employe', 'verbose_name_plural': 'Employes'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RF', 'Responsable Financier'), ('DG', 'Directeur Generale'), ('DEV', 'Developpeur'), ('DT', 'Directeur Technique'), ('RH', 'Gestion Humaine')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SRH', 'Services de gestion humaine'), ('SR', 'Service de Reseau'), ('SD', 'Service de Developpement')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('en cours ', 'En cours'), ('annuler', 'Annuler'), ('valider', 'Valider')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('remboursement', 'Remboursement'), ('prime', 'Prime'), ('CHECK', 'Cheque'), ('CASH', 'Espece')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
