# Generated by Django 5.0.6 on 2024-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0028_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgMt', 'Conge Maternite'), ('cgE', 'Conge Entreprise'), ('cgM', 'Conge Maladie')], max_length=4, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DG', 'Directeur Generale'), ('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier'), ('DEV', 'Developpeur')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SD', 'Service de Developpement'), ('SRH', 'Services de gestion humaine'), ('SR', 'Service de Reseau')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('REJECTED', 'Rejetée'), ('APPROVED', 'Approuvée')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('remboursement', 'Remboursement'), ('CASH', 'Espece'), ('prime', 'Prime'), ('CHECK', 'Cheque')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
