# Generated by Django 5.0.6 on 2024-10-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0029_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite')], max_length=4, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='genre_employe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DG', 'Directeur Generale'), ('DEV', 'Developpeur'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SR', 'Service de Reseau'), ('SD', 'Service de Developpement'), ('SRH', 'Services de gestion humaine')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejetée'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvée')], max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CHECK', 'Cheque'), ('remboursement', 'Remboursement'), ('prime', 'Prime'), ('CASH', 'Espece')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
