# Generated by Django 5.0.6 on 2024-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0031_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgE', 'Conge Entreprise'), ('cgM', 'Conge Maladie'), ('cgMt', 'Conge Maternite')], max_length=4, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDI', 'Contrat a dure indetermine'), ('CDD', 'Contrat a dure determiner')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DT', 'Directeur Technique'), ('RH', 'Gestion Humaine'), ('DG', 'Directeur Generale'), ('DEV', 'Developpeur'), ('RF', 'Responsable Financier')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejetée'), ('APPROVED', 'Approuvée'), ('PENDING', 'En attente')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CASH', 'Espece'), ('CHECK', 'Cheque'), ('prime', 'Prime'), ('remboursement', 'Remboursement')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
