# Generated by Django 5.0.6 on 2024-10-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0032_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgM', 'Conge Maladie'), ('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite')], max_length=4, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('DG', 'Directeur Generale'), ('RF', 'Responsable Financier'), ('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique'), ('DEV', 'Developpeur')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SR', 'Service de Reseau'), ('SD', 'Service de Developpement'), ('SRH', 'Services de gestion humaine')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejetée'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvée')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CASH', 'Espece'), ('CHECK', 'Cheque'), ('remboursement', 'Remboursement'), ('prime', 'Prime')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
