# Generated by Django 5.0.6 on 2024-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0033_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abscence',
            name='type_abscence',
            field=models.CharField(choices=[('cgE', 'Conge Entreprise'), ('cgMt', 'Conge Maternite'), ('cgM', 'Conge Maladie')], max_length=4, verbose_name='Type de Conge'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='contrat_employe',
            field=models.CharField(choices=[('CDD', 'Contrat a dure determiner'), ('CDI', 'Contrat a dure indetermine')], max_length=3, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier'), ('DG', 'Directeur Generale'), ('DEV', 'Developpeur')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service_employe',
            field=models.CharField(choices=[('SD', 'Service de Developpement'), ('SR', 'Service de Reseau'), ('SRH', 'Services de gestion humaine')], max_length=3, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('PENDING', 'En attente')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('prime', 'Prime'), ('CHECK', 'Cheque'), ('remboursement', 'Remboursement'), ('CASH', 'Espece')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
