# Generated by Django 5.0.6 on 2024-10-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0036_alter_abscence_type_abscence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste_employe',
            field=models.CharField(choices=[('RH', 'Gestion Humaine'), ('DEV', 'Developpeur'), ('DG', 'Directeur Generale'), ('DT', 'Directeur Technique'), ('RF', 'Responsable Financier')], max_length=3, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejetée'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvée')], default='PENDING', max_length=9, verbose_name='Statut '),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('CASH', 'Espece'), ('remboursement', 'Remboursement'), ('prime', 'Prime'), ('CHECK', 'Cheque')], max_length=13, verbose_name='Type de Paiement '),
        ),
    ]
